### ISSUE TITLE
Feature Request: only show a video once if in multiple feeds

### ISSUE THREAD

**Issue by kirkins** [dtube/production#15]
I have a video which is in subscriber feed, trending, and hot.

Given there are only around 50 slots on the front-page it is annoying to see the multiple video so many times.

![screenshot from 2018-03-08 18-34-50](https://user-images.githubusercontent.com/9503662/37182647-4e46d3da-2300-11e8-8948-f820d556674b.png)

**Comment by skzap** [comment]
That's an interesting suggestion. At the moment it's like that because of how we store videos internally, and it wouldn't be easy to achieve it without keeping those videos visible in all the subpages like trending and hot.

I believe our homepage to be very low quality part of our website right now, and if we want to ever remake it into something better, we clearly don't want duplicate videos on it.
