### ISSUE TITLE
Custom Thumbnail Gives Undefined On Steem

### ISSUE THREAD

**Issue by ghost** [dtube/production#31]
Hi,

When I upload a video using my own IPFS server (including the thumbnail) and provide all custom hashes (240p, 480p, 720p and snaphash) and click 'submit', my Steemit post shows the thumbnail's hash URL as undefined.

IE: `https://ipfs.io/ipfs/undefined`. This has happened for all the videos I have uploaded via this method and someone else has said they had this issue as well.

Thanks!

**Comment by skzap** [comment]
This is because the picture on the steemit post is actually not the one we use on dtube. SteemIt / Busy.org require images larger than our snap pictures so we generate another one that we put in the body of the steem content, and it's about 3 times bigger than our snap I believe. This is to ensure DTube contents show a picture on mobile devices. 
See related Steemit issue here: https://github.com/steemit/condenser/issues/2409
